.gitignore, api-server/apiserver.py
Useful when we mount `.registry` as a Docker volume.
=> feat: Allow empty registry directory before cloning

README.md
This is with the intention of making it clear what the reference is about without requiring implicit prior knowledge.
=> docs: Add links to external references

Makefile
There is a symlink at `packages/composer/@sentry -> packages/composer/sentry` that was being incorrectly removed via make.
Since we're updating the call to `find`, also update the `find` usage in `sync-all-links`.
=> fix: Only remove symlinks to *.json

azure-pipelines.yml
Ensuring in CI that `make sync-all-links` was run and symlinks were committed will prevent future occurrences of problems like the ones fixed in #21, #22 and #23 to repeat again.
=> ci: Ensure symlinks are kept in sync

README.md
After `cd`'ing into the `sdk` directory, the `packages` directory is `../packages`, not `./packages`.
Further simplify the line by removing the trailing slash from `sdks` and the dot-slash before `<sdk_name>`.
Clarifies the question in https://github.com/getsentry/sentry-release-registry/pull/15#discussion_r379468498.
=> docs: Fix instruction to add New SDK

packages/cocoapods/sentry-cocoa/5.0.0-beta.6.json, packages/cocoapods/sentry-cocoa/5.0.0-rc.1.json, packages/cocoapods/sentry-cocoa/5.0.0.json, packages/cocoapods/sentry-cocoa/5.0.1.json, packages/cocoapods/sentry-cocoa/5.0.2.json, packages/cocoapods/sentry-cocoa/5.0.3.json, packages/cocoapods/sentry-cocoa/5.0.4.json, packages/cocoapods/sentry-cocoa/5.0.5.json, packages/cocoapods/sentry-cocoa/5.1.0.json, packages/cocoapods/sentry-cocoa/5.1.1.json, packages/cocoapods/sentry-cocoa/5.1.10-beta.0.json, packages/cocoapods/sentry-cocoa/5.1.2.json, packages/cocoapods/sentry-cocoa/5.1.3.json, packages/cocoapods/sentry-cocoa/5.1.4.json, packages/cocoapods/sentry-cocoa/5.1.5.json, packages/cocoapods/sentry-cocoa/5.1.6.json, packages/cocoapods/sentry-cocoa/5.1.7.json, packages/cocoapods/sentry-cocoa/5.1.8.json, packages/cocoapods/sentry-cocoa/5.1.9.json
The `main_docs_url` for sentry-cocoa releases 5.x.x pointed to the old https://docs.sentry.io/clients/cocoa version of the docs. Now they point to https://docs.sentry.io/platforms/cocoa/
=> fix: main_docs_url for sentry-cocoa 5.x.x

aws-lambda-layers/node/base.json
Craft will automatically update new AWS Lambda layer info when publishing.
- Craft creates new files, but does not create new directories. Thus, the directories are created in this PR.
- The `base.json` file, specific to a runtime, contains static data fields that every version file will contain. Version files will contain the same structure as https://github.com/getsentry/sentry-release-registry/pull/30.
=> feat: Add base file for AWS Lambda node layers

api-server/apiserver.py
This PR adds a route so we can read the AWS Lambda layer latest version. This will be used in an upcoming Sentry PR: https://github.com/getsentry/sentry/pull/23036
=> feat(aws-lambda): adds route for aws layer

api-server/apiserver.py, api-server/tests/test_routes.py, packages/maven/io.sentry/sentry-android-core/4.1.0.json, packages/maven/io.sentry/sentry-android-gradle-plugin/1.7.36.json, packages/maven/io.sentry/sentry-android-ndk/4.1.0.json, packages/maven/io.sentry/sentry-android-timber/4.1.0.json, packages/maven/io.sentry/sentry-android/4.1.0.json, packages/maven/io.sentry/sentry-apache-http-client-5/4.1.0.json, packages/maven/io.sentry/sentry-jul/4.1.0.json, packages/maven/io.sentry/sentry-log4j2/4.1.0.json, packages/maven/io.sentry/sentry-logback/4.1.0.json, packages/maven/io.sentry/sentry-servlet/4.1.0.json, packages/maven/io.sentry/sentry-spring-boot-starter/4.1.0.json, packages/maven/io.sentry/sentry-spring/4.1.0.json, packages/maven/io.sentry/sentry/4.1.0.json
This partially reverts #44.
Here we add a small hack to allow some ":"s in canonical names to be treated as path separators (mostly to avoid massive fixes in Java SDKs).
=> fix: Revert maven canonicals and allow colons as path separators

packages/gem/sentry-raven/3.0.0.json, packages/gem/sentry-raven/3.0.1.json, packages/gem/sentry-raven/3.0.2.json, packages/gem/sentry-raven/3.0.3.json, packages/gem/sentry-raven/3.0.4.json, packages/gem/sentry-raven/3.1.0.json, packages/gem/sentry-raven/3.1.1.json, packages/gem/sentry-raven/3.1.2.json, packages/npm/raven-js/3.27.0.json, packages/npm/raven/2.6.4.json
Replaces the current link with the link to the migration doc
=> ref(link): Update raven main_docs_url

api-server/requirements-base.txt
The build is currently failing with error:
```
Step 14/17 : RUN flask --version && flask routes
---> Running in 77b306b2201c
Traceback (most recent call last):
File "/usr/local/bin/flask", line 5, in <module>
from flask.cli import main
File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
from . import json
File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 15, in <module>
from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)
The command '/bin/sh -c flask --version && flask routes' returned a non-zero code: 1
```
This PR implements the fix described in https://serverfault.com/a/1094094/235324
=> Upgrade flask 1.1.0 -> 1.1.4

api-server/apiserver.py, api-server/tests/test_routes.py
This adds support for directly selecting a download link for a specific package on a specific architecture. This can later be used to build a better replacement for `get-cli`.
```
$ curl -I http://127.0.0.1:5000/apps/sentry-cli/2.0.0\?response\=download\&platform\=windows\&arch\=x86-64\&package\=sentry-cli
HTTP/1.0 302 FOUND
Content-Type: text/html; charset=utf-8
Content-Length: 365
Location: https://downloads.sentry-cdn.com/sentry-cli/2.0.0/sentry-cli-Windows-x86_64.exe
Digest: sha256=XH6zBy7cSQHQIJUVWw0bMMADxTsl5KoN0hsx5RDBveI=
Access-Control-Allow-Origin: *
Server: Werkzeug/0.16.0 Python/3.8.12
Date: Wed, 27 Apr 2022 11:14:21 GMT
```
=> feat: Add download support for apps

packages/nuget/Sentry.Maui/3.18.0-preview.1.json, packages/nuget/Sentry.Maui/3.18.json, packages/nuget/Sentry.Maui/3.json, packages/nuget/Sentry.Maui/latest.json, sdks/sentry.dotnet.maui/Sentry.Maui
First release of the `sentry.dotnet.maui` SDK
(Wait to merge this until we publish it to Nuget)
=> Add .NET MAUI

LICENSE, api-server/setup.py
Based on suggestions [here](https://www.notion.so/sentry/Open-Source-Legal-Policy-ac4885d265cb4d7898a01c060b061e42#42a648e57caf44bd8c4b25c7162dbbb3) and [here](https://open.sentry.io/licensing/), picking the MIT license (the service can be e.g. used for checking SDK updates), but no super strong opinion vs Apache 2, for example.
=> meta: Add MIT license file

.github/workflows/lint-pipelines.sh, .github/workflows/lint-pipelines.yml, gocd/pipelines/release-registry.yaml
This adds deployment configurations for GoCD, the new internal continuous deployment tool. Please refer to the [Freight Migration Guide](https://www.notion.so/sentry/Freight-Migration-Guide-2bd47bb683254077ad31e7ad625345ae) for info on how to coordinate GoCD deploys during this transitional phase.
=> cd: add GoCD deployment pipeline

.github/workflows/lint-pipelines.yml, gocd/pipelines/release-registry.yaml
With the configuration for manual confirmation removed, the service will be automatically redeployed on push to master.
=> deploy: Enable automatic deployment with GoCD

packages/pub/sentry/7.13.2.json, packages/pub/sentry_flutter/7.13.2.json
add api docs urls for dart/flutter 7.13.2. we'll automate this going forward see https://github.com/getsentry/sentry-release-registry/pull/132#issuecomment-1829393102
=> add api docs urls for dart/flutter 7.13.2

packages/pub/sentry_dio/7.17.0.json, packages/pub/sentry_drift/7.17.0.json, packages/pub/sentry_hive/7.17.0.json, packages/pub/sentry_sqflite/7.17.0.json
once https://github.com/getsentry/sentry-docs/pull/9398 is merged, the api docs urls for packages will be shown correctly
=> feat: Add `api_docs_url` for dart/flutter packages

sdks/sentry.dotnet.powershell
For SDKs that are built on top of another, we append the name.
powershell is based on .NET, and we renamed it as such:
* https://github.com/getsentry/sentry-powershell/pull/42
=> powershell is part of dotnet

Dockerfile, api-server/requirements-base.txt
Temporarily switch from `mywsgi/uwsgi` to `granian` in order to verify whether it solves the *weird memory usage shape* we see in charts.
=> chore: switch from uwsgi to granian

Dockerfile, api-server/apiserver.py, api-server/requirements-base.txt
As per title, this bumps dependencies to solve the resolution conflict between `granian` and `flask`.
The pinned `flask` revision should be the latest available before they dropped `JSONEncoder` and refactored the whole `json` module. Upgrading Flask further would require refactoring the custom json implementation in `apiserver.py`.
=> chore: bump dependencies

bin/semver.py, bin/sync-links
The script to run in order to add a new SDKs uses Python 2.
I don't have it installed and it seems it's complicated to install it with brew.
This changes it to use Python 3.
I've used 2to3 to check for any necessary changes and the only thing it suggests is this change in `bin/semver.py`.
I don't think that change is needed but it won't hurt either.
=> ref(scripts): Use Python 3
